### ISSUE TITLE
Framework 4.5 causes a runtime error

### ISSUE THREAD

**Issue by nik1t0zz** [lisa-lionheart/TrafficReport#1]
In the solution you target Net 4.5, which for me causes a (funky) runtime error. Changing it to 3.5 fixes the problem.

**Comment by Farmy** [comment]
I got no error at all (only after using the debugOutputPanel I saw "Failed to load type System.Task from ..." - Error. Now I got it to work, but only for querying cars. If I query a building or road segment, the game freezes forever

**Comment by nik1t0zz** [comment]
Those log calls through debug panel crashed the game for me. Comment the code in those log functions and it will work fine.

And for me .Net 4.5 compile caused a TypeLoadExeption on System.Action (!) pointing to TrafficReport.dll. Go figure.

**Comment by ctolkien** [comment]
Can you even use .net4,5 within Unity? I thought it was based off of 3.5?

**Comment by lisa-lionheart** [comment]
This may explain a lot, I just got the latest version of Visual Studio and went with mostly default options, I don't really know much about .NET or Unity.

Oh yeah and the DebugPanel is very much not thread safe I've pretty much stopped using it I'm using a cygwin shell with "tail -f" on the output file to display logs, it works a lot better
