### ISSUE TITLE
Problems with Traffic report button and panels

### ISSUE THREAD

**Issue by armarayo** [lisa-lionheart/TrafficReport#20]
Traffic Report button is half off the screen, but that can be dragged and saving city saves the button location. But still the small instructions panel prevents pressing info view buttons.

Traffic report tool 2.0 button is off screen and the box prevents pressing info view buttons.
Also: Traffic Report Tool says wrong version in content manager.

**Comment by lisa-lionheart** [comment]
Confirmed

**Comment by lisa-lionheart** [comment]
Should be fixed now

**Comment by armarayo** [comment]
I enable the mod but cannot see the button anywhere.. Hmm.. Perhaps make it like Advanced Road Anarchy, the button appears in the middle of the screen and then it's dragable and the location is saved :)
